apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
spec:
  rules:
    - host: vaultwarden.lampe.wtf
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  vaultwarden-service
                port:
                  number: 80
