apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
spec:
  selector:
    app: vaultwarden
  type: LoadBalancer
  # loadBalancerClass: tailscale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
