apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - namespace.yaml
  - pvc.yaml
  - bootstrap-job.yaml
  - postgres
  - plex
  - overseerr
  - sonarr
  - radarr
  - prowlarr
  - qbittorrent
  - bazarr

generators:
  - secret-generator.yaml
