apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - namespace.yaml
  - pvc.yaml
  - bootstrap-job.yaml
  - plex
  - overseerr
  - preparr

generators:
  - secret-generator.yaml
