apiVersion: v1
kind: Secret
metadata:
    name: media-secret
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:PXAmQpS8qC3z+V1LQVFGvibWyl4=,iv:73tkOADxHBZuvLNk5xdhdLFtmCSWz+FgWLmLmxwtYEU=,tag:+pcq/44V/jFRD3x1A0WvVQ==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MEV3Yzl0MVdCU1hkNmcr
            NlV4eHAwRHFvVkJZRjFLWTUzRitKV0o1SWtnCnVKM2FvN3ZHNzM0V2JjbXFYci9M
            bzR2TVRTNWRCaEVnZVRvYXRGWURwSHMKLS0tIFNtOEt6WEpnaWJLM1RsSjdZTE9u
            Z3dtdGc2Z01FaTdWUHZHSFFMcElCRGMKKpYo/pbypKuQ2hwh246GRu1/dyOQ4760
            /PxCgABhWzaxfhv2maRxXekpPM9MKM+5no94aAkLss2mSIdXTBAeRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T21:06:39Z"
    mac: ENC[AES256_GCM,data:lL3fJxU/4sndv9/IT7NsyVUKBTgCZTiTsLXU6DgclDM2NdG/2lZXIbSB1IIoRVkAB2x3inH9U3dUijhUakMDzrlrHgnNc5i5bn2v/Dzd67EISvOmegZudsii3/9jB9zKZ70h2itInMOdhhhaTH+LEUkGA5fO9S49fCVd6710Ku4=,iv:SA1JUd1AojZs5zvZ/Odt/xcVFX7Vqpk2WDKLIeeFobk=,tag:/QkRYKc6S80UfYH1huCu4w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
