apiVersion: v1
kind: Secret
metadata:
    name: media-secret
    namespace: media
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:TlVgHd8QdnJ8zyuMeYIUYWVuXxw=,iv:Z8cz/q8uR+/UlBHgMkJ3fywvQ5BL9RK6loNGaeSxabw=,tag:qZofePG7ddX/yCccm40rWw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:2/CE7CwQ3F9rFk+wnDfyXEXYVw1BFdFQzKR7r9rRrFM=,iv:tCk8QEqueewbp0MHcQ6mJQj4jb0g0lws4mI55UDhMyc=,tag:kFPt4sqX9biNi4P1pWwNDA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:h7gc/SI7Wc0jco01f2KxWTZZpG6IUPyPlMhlHO66kGk=,iv:c7ZA3El5dp4n6BLBlyY6v/5mz0ER+UbQHzMZ65e59vM=,tag:GaWwVMqOEWlLFXys2OQorQ==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:PQ1rYJpMe1oFlUXXrRbX/oX7pucvriQX4Y6Kv/5wNjE=,iv:ZBbJZcPUXrgtG8lmH4Dy6ftVrrYwyLYqy41fABl+DVQ=,tag:b4vDUAS5CP3bdKLhU+tHWw==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:5HMxTc0TH4S6dkDUalkP6Qv2/O/FpTDn2cLu9A8cQbQ=,iv:1vPzanw7wYoNxiI3pWJAlWS0FWf+BH186i3sbS5NKPo=,tag:bH5XHJmXsCLb0KITwfF2EA==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:tU7upON3Dwf5ktQ8vDimycCdcoaaVoSe,iv:k1AVp09dqt5SM4FVkXcanIFgNF1TEnoYUdM9W/AUlTI=,tag:qPZtgY/E+k2hpeUaJqFSWQ==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dDNFTUI1ZHAzclFJbXdn
            cWROLzgyZzBNTlUrTzNCN2xZM3Y3YTFOQjJBCkpGa3VRV2tSd2ZEYk42Y1ZuRU1y
            TmZoWXkySW05ZVFFWFlJZG1vbDF6VFUKLS0tIDBBV0NPSHJNeFFCL2EybVBPOVlq
            RS9rb3RzVGl6TC9iSWpQSVIxL01HOG8Ko4FzPS++gmv9js0KQRM2Th5Cwy4ilnef
            QZe5FxS1T4mE6qzB3coJjvu4XeiAsIdmvwslhd//f3MJk6EoV9yU1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T05:30:10Z"
    mac: ENC[AES256_GCM,data:6ErCqv81Tthx7/xfGm6E2FeJZQ4l5W2ZtLXxaUaxM7mFVv1pt/JEH/zf1BADyvHxZHNkMgSSlqyi8eujYEYNaOrKboZQp6VDf+S7KymGtWCrZUDkEWstBHjyrwOV/Lp/3JnlJLSkVuLcrzLvonl98lR3XlZNq4Ego7jvIcYCAbk=,iv:x3PbBvemY2cqxgns7fCBdfmq7L8Rg1yT3U++7YkSitM=,tag:l4f6Lhikw8t2bZ1oYADZ/Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
