apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: plex-media-server
    repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    # renovate: datasource=helm depName=plex-media-server registryUrl=https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages versioning=semver
    version: 1.5.0
    releaseName: plex
    namespace: media
    valuesFile: values.yaml
