apiVersion: v1
kind: Secret
metadata:
    name: adguard-home-secret
    namespace: adguard-home
    labels:
        app: adguard-home
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:GKQjW2oFfkuq,iv:mQg0HeX/AqTaX9NQTLnUs+VuRk9noItJxqNKHPyWd10=,tag:ZRG2AoyCALojI5/jw9oPrg==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM1lrY0JtTGtvNFgyU2JR
            ZTBUeC9MTnpKNjA3ZjllaWF1aG1va296MjE4CjZEQXBGTk1QRFhQeUhMRXY1ZWFN
            K0NyQ0ZMSEE3Zy9iSWk1SlZzLzVNRjgKLS0tIGFqcWVYOHZnTmo5M0dYb2lPR2I3
            NkNnNWFUWDVFblBERzFzNjJDa0hMalEKVNZcOPqcoKz2PJzIjhqdSSVt4Wc6FE9b
            qiDWWLYjaelAojNctirPdwILJ2CBNwBXtEqwYNbmMxaiDQaEUpjOBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:30:22Z"
    mac: ENC[AES256_GCM,data:Sa0JJRTrn+yyKUpVitE5u4j0hDlXwplkrmXGLfK0f5URjFqozxq+uy01RnmKRzRXZpDPwMx397i/vIUWUh5WaH0pUkKj91EWxFKty0fTWvSGZyxQXLFFRT7ZATjNgBEZP5wo2dgLjewV4AaedLCKWPm4shlFeEID6NBcxMRhaI0=,iv:UvY525LnFjYM3mDZnIqss7e1I4jAUzne0qc73zrPCSQ=,tag:1MgTumgY54ML++/NefdOwA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
