apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:d5c606KwINlvnAI0sQDd1kU=,iv:siwbtSzWsjXt6qTUAa1ynn2OTL9E4Or0LV7lpq9pDew=,tag:MrgBEvNO+sHsvDbZw+uBDg==,type:str]
    client_secret: ENC[AES256_GCM,data:QGkYO5+1YA4xKmN+7I2W69TgRvseiXmZomFDqCy+yQgixAOgmxDBbhcojZEGAP20ihz1MheBXtGXXXp+xH2cBQ==,iv:b2BDBXMPwpMQQ6botwygLIS4S4220Hj2wE46yvKwWDA=,tag:yW6yq2e5JKY3zKM/QHwvvw==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeXdnMW5xY0hMRm5xeUF1
            NnNacmNlMmR1UHRHOXl2bCtOOUFVMEY3S0M0CkVDekh6UnFlWE1LaXV3UURuTFZl
            ZWtKTVJhcjlwS1NoZkh2aWU5ZENrcDAKLS0tIEc3ekY1SVB3TkllSS9FaVZkRW56
            QUZ1OVpvVmJNQ083Y3JFWXV4Mm8xOGMKdVmkS+YmjCdwqlLPMCz86GkH6TwLwqwr
            NH3Rzw09FSnOA6eOyPzHR4u8lsjTWNhmC9svMDfT97wzwSh7jv518A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:33:00Z"
    mac: ENC[AES256_GCM,data:8A9l6j3wLPASkeitcgSo/hO9xnViyXWv195O+u0fipn78RHTCmx4yu6Zi7kUkx6yJTFBNc8hequfiF+uwlc5d6LtrrQ6fXNGQkZrMaKKbENdMnMISJAwsREnTxHWRHm6+/6ScGRoKZpHDY+Kekd9BJJYzBuNsbl5IvsrajwtrCQ=,iv:qcOfWlwo1lGb5aMINv5B1ZVh2lzqYFw+akz25Mua2ks=,tag:VaNTRNHbqbboCzwUnDFZBA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
