# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nextcloud
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/nextcloud/helm
#     path: charts/nextcloud
#     targetRevision: nextcloud-4.6.8
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: nextcloud
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     automated: 
#       prune: true
#       selfHeal: true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m
