apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: matter-server
        # renovate: datasource=docker depName=ghcr.io/home-assistant-libs/python-matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:8.1.0@sha256:170aa093ce91c76cde4cc390918307590f0f5558fcec93f913af3cb019e6562a
        imagePullPolicy: Always
        securityContext:
          privileged: true
        args:
        - --storage-path
        - /data
        - --paa-root-cert-dir
        - /data/credentials
        - --primary-interface
        - end0
        env:
        - name: TZ
          value: "Europe/Vienna"
        ports:
        - containerPort: 5580
          name: ws
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: matter-server-data-pvc
