apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data-pvc
  namespace: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
