apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - namespace.yaml

generators:
  - secret-generator.yaml

helmCharts:
  - name: velero
    releaseName: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 12.1.0
    namespace: velero
    includeCRDs: true
    valuesFile: values.yaml
