apiVersion: v1
kind: Secret
metadata:
    name: velero-cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:Lr4qyORGlnTGMzY5m670BZLTbXLbxBoJOJAyG3amt2M8q+UMjqVap8+OOTfU8T8i1g2nX78IQTsGPFOkm1i8m6LqtO841ZUdA9yxs1rHzIlqqeLB3pk0rNvCvMMPJ33wHt2bl7tU8YpeFPWq5tQVXi6euecSzT8qdnSnt9u5YR14Qw3lQy9kLQye/6hpSAJnamcwLQQA,iv:9Me6LSWXsBSrJyI8VU0uQ3pSiyod/dfZBiQCVGQfz34=,tag:cvGnjKv04k8J3LF2BLmzcA==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNTB3M2Y5ZVBMZUFJMXE2
            bmRjVVNNYjJ4MnBBbUJZcWdsbzJUUHJtb0JNCkhHVHhZeWhxYlZWWGxVWXM5Yldq
            OXE5azVjZHBuV09tWk5BZ3dvOWNIaG8KLS0tIDdTTEJXWFoyb29FeHZWdjl6M0dX
            enhnTE9rSGVRc2ZuQW1ITDU0VWZvOFEKjsz/SX+Uf/5Idr1n93mjHSPPu/aBT2NR
            CLGQF1PW2p4m6j7vjvaE8X9hB9JjDhVI1nleKpS0ge7jQ5GXkxSAlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:10:19Z"
    mac: ENC[AES256_GCM,data:uo9UjXdnnE5BXbx5qH4UyQirhX219irLbig/NQxljeby/Z0uPfOPkzoEIG5oGjJDRMP76ikmEJ8McPdzgIaoQOV4pxg9OaOPOhfdHFINzNb0+FK7TJreMJFGgim37u531N7Ygt4iv3DGmxy+Wx5vfxulniGltiOFnLsT8HWHfhc=,iv:o2Go4dnbncLRE/hpR1QdYSfPaky8JeYKSSlodTzxCgk=,tag:cmr/Mis+6OrwjY4VRGgjRg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
