initContainers:
  - name: velero-plugin-for-aws
    # renovate: datasource=docker depName=velero/velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.1@sha256:1493a0039cd5cb31004cfbb52f8a1990bc0ed81497ce72516bc76fa9e21506c1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: velero-cloud-credentials

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: backups
      prefix: velero
      default: true
      validationFrequency: "1h"
      config:
        region: garage
        s3ForcePathStyle: "true"
        s3Url: http://10.0.0.11:3900
        publicUrl: http://10.0.0.11:3900
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: garage

deployNodeAgent: true

snapshotsEnabled: false

schedules:
  daily:
    schedule: "0 22 * * *"
    template:
      ttl: "168h"
      defaultVolumesToFsBackup: true
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
        - media
      excludedResources:
        - secrets
  weekly:
    schedule: "0 22 * * 0"
    template:
      ttl: "720h"
      defaultVolumesToFsBackup: true
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
        - media
      excludedResources:
        - secrets
  monthly:
    schedule: "0 22 1 * *"
    template:
      ttl: "8760h"
      defaultVolumesToFsBackup: true
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
        - media
      excludedResources:
        - secrets
