initContainers:
  - name: velero-plugin-for-aws
    # renovate: datasource=docker depName=velero/velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.0@sha256:7e82f717f44e89671212e0dfce7e061321c386ea84a33bca64a671670ca6c278
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: velero-cloud-credentials

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      validationFrequency: "1h"
      config:
        region: garage
        s3ForcePathStyle: "true"
        s3Url: http://10.0.0.11:3900
        publicUrl: http://10.0.0.11:3900
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: garage

deployNodeAgent: true

snapshotsEnabled: false

schedules:
  daily:
    schedule: "CRON_TZ=Europe/Vienna 20 18 * * *"
    template:
      ttl: "168h"
      defaultVolumesToFsBackup: true
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
        - media
  weekly:
    schedule: "CRON_TZ=Europe/Vienna 10 0 * * 0"
    template:
      ttl: "720h"
      defaultVolumesToFsBackup: true
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
        - media
  monthly:
    schedule: "CRON_TZ=Europe/Vienna 15 0 1 * *"
    template:
      ttl: "8760h"
      defaultVolumesToFsBackup: true
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - velero
        - media
