apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secret
stringData:
    licenseKey: ENC[AES256_GCM,data:ltSXhg==,iv:MYzD8PGDkJTVt2lpeBVYlHJzwcUVkt++YDLaWEJ67I4=,tag:M5yOs4mzY2IUCmZaDP7F+A==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVnJTaWdNVWU1aUZrZWZY
            aHZBSmp2UmxmRGFOYU43NzFGY0lCTUNoTERnCkttZW16VXBsTDFGa1hsQkthTTBG
            YTFDQ3JiNnJCMi9DbUh1aCtpZ1RGWlUKLS0tIHpjZHA3cG82Y3FRR3Y1MFgyTUhO
            R282aGVjRlQrMldHMmxva21sNC9TYk0KuwTjwZMShrZkG9MC+8BaVc8oTnwvELi4
            URKhrA/ae1Fgi/2FeO6A+p/UU1yGjBDFuDbcvGwv5Z4gvmCd5h0CuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:17:11Z"
    mac: ENC[AES256_GCM,data:8w4F0WKjcAVdDDomh6MiRMgcIAfKIa6E1Mmb7GbNbqYh0CL/ESBQiqUj9QuT83Ue5szjA8opSLpkK4enY8mZkmm5uOZxlObFdJXpq4RWfLt2fYQl+Rfp4hRkrbisbX0n5qH91+z8ssKEmC+NPIzguHJEYT6tWJouOOwZ9xt5P20=,iv:lA69hSwDiDK2yyzzvZav9+btq+qCVW+l6xhKjSZAnOc=,tag:GHfkoD9N8rXylilLS7gXBg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
