apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secret
stringData:
    licenseKey: ENC[AES256_GCM,data:Snhi/g+ip3Av3g==,iv:fVIh+N3y+1MCcLi+Paq6Im5MTVR/a0EqmO1qimYcONw=,tag:EkeLVTsVIO/Ep2ER9XR0bA==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NUlnY29iclAyMDdSeFZn
            cG5wODU0TnFKNi9rZDBQanN1b2dNMFVLb0QwCkRZY0tGdmpTVVVDMXpxMEtGeHBK
            bWF5c3hXTEcrT2dCYm00TlE1RzJyTUkKLS0tIE5yTUtFZW4yZmFGcU9saFFlbkJn
            NnVETldRT2k3RVd6bkNZWXdRQ01wR1UKZ492RsYrv3AVQ8jFFT7fyEjfjCqNToRe
            Qq0JM+4qkLcYdxPVqI79/5ryYowATjRwmlYmIx01HZAvWiCmOQ0QTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T17:49:08Z"
    mac: ENC[AES256_GCM,data:3dfbuohteVneWxjjXW+O4k/WhrH8q4PYhJLBj/uoe/097tAPaNCaoqS7DxA7ZwbiF8tHaDxchdf7HXkzc4ZnnNOconCvacZG5NDi3n267YEBUVHwFXawu+DJJoddbcUmIvnuQKXk6LnBgfIbhzuza/ff/QGYjTjAEoU/WoM+enk=,iv:cd+Y6w0SYt+ebNeGgrHXnFwuCeH9U3DGjzgKubsNi5k=,tag:uiJ3PzFdEam0Fgxj+eQQlQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
