apiVersion: v1
kind: Secret
metadata:
    name: newrelic-secret
stringData:
    licenseKey: ENC[AES256_GCM,data:Ck5f3VXP450Z0g==,iv:Ib395VXlwoEkiLjWypicELFqmejazg3nzXfQfk2POl4=,tag:M3y4VHvtvZPRRNeo/3wZtA==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVnJTaWdNVWU1aUZrZWZY
            aHZBSmp2UmxmRGFOYU43NzFGY0lCTUNoTERnCkttZW16VXBsTDFGa1hsQkthTTBG
            YTFDQ3JiNnJCMi9DbUh1aCtpZ1RGWlUKLS0tIHpjZHA3cG82Y3FRR3Y1MFgyTUhO
            R282aGVjRlQrMldHMmxva21sNC9TYk0KuwTjwZMShrZkG9MC+8BaVc8oTnwvELi4
            URKhrA/ae1Fgi/2FeO6A+p/UU1yGjBDFuDbcvGwv5Z4gvmCd5h0CuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T18:00:05Z"
    mac: ENC[AES256_GCM,data:fN/cViNN4fLDejqmD5PIxjibSOcpZj/IB92ilOT0g0WyNGCRvJN9cCsrtO8AwYrvdTocKJMvFr/Py90N6dq+7gos8VGWUbUdGMZmzUJkh9cIKlmpTvJpexEU6F8/Iv945V+qjTAV5MC7A+LX2YAcZRMeZl5QrwGV40OAhBdh9XY=,iv:uu9pv6qWArhNUjuDoftLcYOUwYM4wxqSJDcldv3DS4E=,tag:G3ittJlaOem2DUMurpDRWA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
