apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - pvc.yaml
  - postgres-objectstore.yaml
  - postgres-cluster-recovery.yaml
  - postgres-scheduledbackup.yaml
  - ingress.yaml

generators:
  - secret-generator.yaml

helmCharts:
  - name: immich
    releaseName: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    version: 0.12.0
    namespace: immich
    valuesFile: values.yaml
