apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-database-daily
  namespace: immich
spec:
  schedule: "CRON_TZ=Europe/Vienna 0 0 19 * * *"
  backupOwnerReference: self
  cluster:
    name: immich-database
