apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-database-store
  namespace: immich
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://backups/cnpg/
    endpointURL: http://10.0.0.11:3900
    s3Credentials:
      accessKeyId:
        name: garage-s3-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-s3-credentials
        key: SECRET_ACCESS_KEY
      region:
        name: garage-s3-credentials
        key: REGION
    wal:
      compression: gzip
    data:
      compression: gzip
