apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1

  storage:
    size: 10Gi
    storageClass: local-path

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  postgresql:
    shared_preload_libraries: []

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - ALTER USER immich WITH SUPERUSER;
