apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1

  inheritedMetadata:
    labels:
      velero.io/exclude-from-backup: "true"

  storage:
    size: 10Gi
    storageClass: local-path

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  postgresql:
    shared_preload_libraries: []

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - ALTER USER immich WITH SUPERUSER;

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://cnpg-immich/
      endpointURL: http://10.0.0.11:3900
      s3Credentials:
        accessKeyId:
          name: immich-postgres-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: immich-postgres-backup-s3
          key: SECRET_ACCESS_KEY
        region:
          name: immich-postgres-backup-s3
          key: REGION
      wal:
        compression: gzip
      data:
        compression: gzip
