apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-backup-s3
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:2xKvODn/gAAkfFwp3s05hr9CvN3miwMWKac=,iv:Xt+gEDKUyQhTNXowsdk7bhtgu+zhGqPu8sOWPcwYriY=,tag:6flNRkL77JTZ1ENOyeHHdw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xEWXMAHbIPa+XzjivK8kE55vNHODUN5HCGI=,iv:24pNB354KRxj8FU1BCxxmLH2Pglho+/iQk7Q/tt8APA=,tag:8gZZybuF8mPLq0l+BK5ZWQ==,type:str]
    REGION: ENC[AES256_GCM,data:k0Yeb9Ta,iv:izZ0YrsPJ7fPhs4uQlf8EuYvxSApTxTOuFBfcbsl66Q=,tag:Yqe55t6yLYzLjGWzADtaLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHNHbUk2b3VjREN3bXIz
            YXgyNnpkVUp3NzZoNTRSeWc3YUllbWF3NG5zCnVrYlRYNUpRKzdzUzB4ekVXNkdQ
            QTEwV1ZxWloydUpHOFd0OGhRbmJaclEKLS0tIElBVFdoUU4vbjNRbUNQY05qYjF1
            MXBXZ1lXWjNqOWF6eC90SkdtdXk3ZXcKJauB+b8GQME55nb1+e/i+gTtykGLmpfX
            U58Y3Kv5WUsIgp0naxt3MxN4J17SowNuy9dbC1upytLgh0tAvVffHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
    lastmodified: "2026-05-22T19:16:57Z"
    mac: ENC[AES256_GCM,data:G1LJKMiKSGzuA1FC/13K/EHyzYjB3j+PtGm+gJq/yeYefrkG1TEhv6dBrcPPkBH8XJ8MIS2W4cOK9JAQC2a96uLMIn0TQ8zyRh6BAjJTdW6DNyfyZCWTWAMdxGWQBcaRBrQ+taCNWz90nuCprjPPH05HhPYEft07nt6p+EWiMKQ=,iv:ZAVKuO/6ZCR8DfZYvGJuYzkrSAvXBjX8rAYE+AtcwLk=,tag:GLl3tCjutsFyTV8SXyjMCA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
