apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1

  storage:
    size: 10Gi
    storageClass: local-path

  # Use the cloudnative-vectorchord image which includes the vectorchord extension
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-credentials
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
