apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-credentials
    namespace: immich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FxZ0nAzt,iv:zD4abveOSixUBXzBX2A8B2rwpmJ8G5QDM8sMXS6UfYQ=,tag:hXkZBEa8X+UaTS8YF01VCA==,type:str]
    password: ENC[AES256_GCM,data:xKTED3tkPkFHr3JuC6qc82JtuvYw+VzOG3351pTOpLj3gw==,iv:Lf8GG6fn8PV9Lp+eHjQ5BONneDNnOeWdGA1kc4qkIlo=,tag:3GCHXBEaMBxHRXtClVMmJg==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONnd0c241c3daVWVvSlo2
            OVY3S2VPOFdOQytpa2JERHNLMUp0cnlOTG5zCmx6WXBkZERzTXFoQ2tTWHV4WUFa
            RHpVZ0NHYlJvZG1ycCtuTGpYd21JMm8KLS0tIE1MSm1aVGlEWm9MdjM2ZGdGaXJm
            UnhUb1I4Rng4bEkraUdXVUV2OWl6UlUKbYLCd1iUJAzS2Mt6fBFbYKKCPr9yxxFI
            3VIK84w9i0VJgcjNDnQ5NSFvh/VF6HofGXuzdPIQUIH9G2FlkiIdMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:30:28Z"
    mac: ENC[AES256_GCM,data:6oIVvMTYyUuzlUm19I/MRor2s/KxfZDm7rILOeQGoc7mRxE6JpiNrFS76sWd29vrmWe16Y6HM5RFfr3mRmuqkas9fqKhdFe/kVHWlgKSNdnYMzK8asVLERu4INSiJWW51a9NEae6peL83oZoZrc/d0MiK9n09t390YpMcDClwzA=,iv:i9A8XWLKIXaq/S0Pf+uXmCPI6TcxXhEYJi2XmWYdFZ0=,tag:aBaWbPNJ6d16a0YM79IBAg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:YAvR/ZBskbsnke4q1wPC0FKT6tOZ32/IQKpTN2qvt8qaAA==,iv:QG0ptfPKa5Z69Jnhz5yj3PwAHGRi1bk5p6cVWcyA95A=,tag:0+Lk0E1vRp9A5ealNBnSoQ==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONnd0c241c3daVWVvSlo2
            OVY3S2VPOFdOQytpa2JERHNLMUp0cnlOTG5zCmx6WXBkZERzTXFoQ2tTWHV4WUFa
            RHpVZ0NHYlJvZG1ycCtuTGpYd21JMm8KLS0tIE1MSm1aVGlEWm9MdjM2ZGdGaXJm
            UnhUb1I4Rng4bEkraUdXVUV2OWl6UlUKbYLCd1iUJAzS2Mt6fBFbYKKCPr9yxxFI
            3VIK84w9i0VJgcjNDnQ5NSFvh/VF6HofGXuzdPIQUIH9G2FlkiIdMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:30:28Z"
    mac: ENC[AES256_GCM,data:6oIVvMTYyUuzlUm19I/MRor2s/KxfZDm7rILOeQGoc7mRxE6JpiNrFS76sWd29vrmWe16Y6HM5RFfr3mRmuqkas9fqKhdFe/kVHWlgKSNdnYMzK8asVLERu4INSiJWW51a9NEae6peL83oZoZrc/d0MiK9n09t390YpMcDClwzA=,iv:i9A8XWLKIXaq/S0Pf+uXmCPI6TcxXhEYJi2XmWYdFZ0=,tag:aBaWbPNJ6d16a0YM79IBAg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
