apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-credentials
  namespace: immich
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: change-me-immich-postgres-password
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
type: Opaque
stringData:
  # Database connection details - update password to match postgres-credentials
  DB_PASSWORD: change-me-immich-postgres-password
