apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 128Mi
  reclaimPolicy: Retain
