apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 128Mi
