apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Text to speech
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
