apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Configure HTTP integration for reverse proxy support
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - ::1
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 10.42.0.0/16  # Kubernetes cluster CIDR
        - 10.43.0.0/16  # Additional Kubernetes service CIDR

    # Text to speech
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
