apiVersion: v1
kind: Secret
metadata:
    name: ksops-test-secret
stringData:
    foo: ENC[AES256_GCM,data:jdZTqw==,iv:bhN95oYcml4+ELNN5S+dK+cDFbNf0LlilyCqQ84QsfU=,tag:y1dPO/uYX3RURXZ3e0Qzyw==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQmFlb2JkekJLdzBUTVZo
            dmh3QThVbmVmZHIxNmFXcy9lWk9CRlNEU1VnClVaZWh4MnZrWm9YRFlORDJTZERS
            MjRlUlZjYlAvZFdrQmxhU3ovWjF4eWsKLS0tIEw4czdtdVB1Zk5NV3lnWFBvNEcw
            RHU5bC9oV29Lb3ZocGRheHJHMlE3ckkKpBF8IeanTSZXfZI8blS5aG4nMAI+xWb4
            qKSQYx0ylW72NaWZyu4IeniRioCD3PKsETkc1lXkQ7olzuN/woZCUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T18:34:54Z"
    mac: ENC[AES256_GCM,data:BFJ+n4uMpBo7ezbnu1eWKnEpWELesBPOGksR0Ez6up0xXp78GzTrW1kuVH8x418vah6KGD5rtGIrsPbN6rVLOOTZ9RSzhgfbmXY5Q6WMV0DLmgVuJBvt+tBSfMsdLaWdjd9+oqs0UUKITA5bbLcIWQ1m2qMky9kIt0kfdPXf1qk=,iv:uR5qjCDglbLyz5ZYtlB55Du8YBZaW70aZlWjKm/xVZw=,tag:O/oSVQlvDg6be8IkexAqpw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
