apiVersion: v1
kind: Secret
metadata:
    name: ksops-test-secret
stringData:
    foo: ENC[AES256_GCM,data:vX2E,iv:ud3W6EfqmE2DQ1gYD38N+X0z+CTCl3Vo2BPB70LQCpQ=,tag:AWgpIjYV6Hmbll+oKqKocw==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQmFlb2JkekJLdzBUTVZo
            dmh3QThVbmVmZHIxNmFXcy9lWk9CRlNEU1VnClVaZWh4MnZrWm9YRFlORDJTZERS
            MjRlUlZjYlAvZFdrQmxhU3ovWjF4eWsKLS0tIEw4czdtdVB1Zk5NV3lnWFBvNEcw
            RHU5bC9oV29Lb3ZocGRheHJHMlE3ckkKpBF8IeanTSZXfZI8blS5aG4nMAI+xWb4
            qKSQYx0ylW72NaWZyu4IeniRioCD3PKsETkc1lXkQ7olzuN/woZCUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T18:33:34Z"
    mac: ENC[AES256_GCM,data:tNKbtd4RqomSluXtEqcN8/yzdHWxUs27ccKgI7zDAhkzIrvKGsOZJ6gR3DD65NjTqRAhAnALMlC0SmUIqTVhTwhnCYodtpM7jcBweGAfE31x24hnsZ77SstbLArkc2udc4OsSobZsanZWLyLk9Akcam4zujJwtjy2GnDUTIllx8=,iv:M631scQeUOtUbwR5GOEmr5vvt4K4WjCAllfGHxoXTb0=,tag:MXLXXjnXo6q0MUhc/ARCGw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
