apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:HXeVwrB8vUQJ0LsSyEMVzyP6cnbHOvHkuiE=,iv:rhEXQLF2bWjWJ1ZrvzRA5Ad7OlMMisiy9+3TflbU5rc=,tag:ulEihuImZoT1p9TGAQWrNw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:b881rzuijLDXMoG+F+Uz4BfqY1/BFO0DDT8=,iv:2VAdNsJL4PwJdHh/sDm/vBLlj1UwnevxphwG8XqTHoE=,tag:PeZOwXKDxYrwPn9VjFz/yw==,type:str]
    REGION: ENC[AES256_GCM,data:w+/qidtO,iv:LmLp4VWWBs2niB42Ygo9EShcaiCg+cYLgTaCaAzvqVg=,tag:LaKHgqTLxELMrKDW4ltU8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM1RxWkNSdVZyY0xMdWFR
            WkVBRUE5QWQ5T1h1OThxWlhYd1hKL0FrRVhZClZBZ3FPYU9xclRwM3FNK0dUeTZ1
            NXRMQ2NSemNuVXZoTEdXL205V3ZkNWsKLS0tIHZZOUFSZmZPc1ZQaVVNL0luYVVT
            ci8rcE9xNnFKQmtqTHNCV25mUmpwSWsKWujNMQkCpQLMXhHNEohCRF4Fkry0h4WX
            btcD9s8O6DOn/DCSDplCKt1Z5/juWMHvS43l4tgw0yghr+P2QgoFXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
    lastmodified: "2026-05-22T22:10:34Z"
    mac: ENC[AES256_GCM,data:SCBLO4OXZuZ+01GGXr3S322/ZWb/FSzdfv28c6Ewqa7FO+QnQrth8dP55NubDoqShzLMvuZ4cKfKK/eedXMszZdwQWKAovpXA2VwL1/l/ysMkgil+Vg+DlDIJcsiIqTJw6V8a8xymZ0yh7rTBDbS8twuu97EimXJo+sTRErVTbc=,iv:HOcwGvev3X+8BDpMRjDwu6bSG6PyMgD8NLAmUIc8miQ=,tag:ZSje8MzJ8BSYcdLQtYna1A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
