apiVersion: v1
kind: Secret
metadata:
    name: garage-s3-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:zZKGuyGwYqgrsI8PhgcsDrgxK2y02+T4rJls0LZaHeggeA==,iv:47X3ohYGUzTopv80fjmoWMJSyaYRTsflNomFmdrDSSg=,tag:KvW+snOs/09Vv5sohli+KQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RqNtgjSwBXG9p47E0rZCgzRyWv7v3UP8hKF/0JsCOZqa+h+fEI4AoNaFlvZlPlEtc3Yrz4VxAO+hOXK6KKgBMw==,iv:ZkDDN6SJtt43o3xeDUNAEXU5WreQdhNMQn0WnoEcy24=,tag:KQvOK3AZkP4lnrh2ggPPYw==,type:str]
    REGION: ENC[AES256_GCM,data:gFoTc8XD,iv:R0oaoHesxfIBTQqnHYkE9wE9HRzvtrjlR+uZ6Y4S/pg=,tag:5jWswi2s0pJjgkOdZGJU5Q==,type:str]
    cloud: ENC[AES256_GCM,data:6KIHcNtc0h7IhZwPMj2cnoSyvPLks7Rvib+uis2nOT3WM3ViyvxCcMW32ZDxSR2c60RHZQkrKve9PUOxl+sfxq3vODaP0MQiknmu7cv9mX8YJ0WoZ3eycX87GYEYktjrst/OMysD7tSEOD0yzzwvHrW1l2HAhbl1032zRXT9wk24eLC+obntEcwRDM0mPw2xDT5apzDu,iv:oOEeW7UNYAt9zc9aqRHBfeLtLAT+7vJR+IPKMByEjZY=,tag:2jrRWWTs7U+qDYl7wpnBeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNDk4Y1h4bVdzNHRPQ3ZM
            MWdKVFhvNUF6T2cxUlhIWnIzWVZTMTFxVzJ3Ck81QndLaUhRV1A1VzV3aUdWcis2
            aC9Ibk9pakhQS25CSFhNSjAwc3M4Z1UKLS0tIGVWV3R2SVRqdXQ5MEFteHhkWHpT
            MGZXM2xYNTViUjBRMjlPcmt0cEJHN00KHn48UD13U7O5+tn9RgaYl1BcHRMVuswJ
            VyP61c519DjCrrLJ2zLQtR+y9tdLO1SS3a5UJZ6iqCSGvafoBsQ3rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
    lastmodified: "2026-05-22T22:15:31Z"
    mac: ENC[AES256_GCM,data:uRm/7t1vPrljF9CA3WDSB9x1yn8eyjhSmeSMC2/d06+QeA26XMhbV1ZvY9B2rVjf2FObtMfpl7BtpFAbldcAjtZ9FvyIT06nyqQi2Bsx217Ix9h+Gqb0wN1jw4v9+nftICQ4sq+nqKDPEG70F8eHqVJ8Hk7UZtbF6m3SoS6aKOk=,iv:s3dan2J9bePckytKKTcCWLN46BEqr8J4Aoopl1W5evY=,tag:0oD3eOSix5y9csHHa6aNFQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
