apiVersion: v1
kind: Secret
metadata:
    name: garage-s3-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:5KmxP9dPeiGnmjcjgMzf6vudQj3PtdypHT8=,iv:iUQoGNsTHmwL4DnNGBZJN/1bTURpnSsYVd2PyIeeiDc=,tag:8ds52ifQF1/jdjXtQ8usHQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2ATMFlW1fbKQUmHLuvW6tGISkAN8mh5gUDM=,iv:1k26iOjQIw9liwEpVVLOzYlyZ5podDg1kfOjY//3oTc=,tag:+X5hXIEN02HpXcrCCzSHqw==,type:str]
    REGION: ENC[AES256_GCM,data:DI0K/qW+,iv:2hV2MdRTjpsatDbZaAharw+4H1Q9YtDPh9Gy5YnXJvU=,tag:d1aTuxMKRYDeWsGK9JG2Fw==,type:str]
    cloud: ENC[AES256_GCM,data:JKH9mWJFDsrWcREMyoWNhY8xvH+DCEtKU45ePfUWNm6QGisq5AtuLYQ2giB510ARC9vksNygbSI/a+hn8vXGPGvRr7zybqQ7B+EccxrVCfs1/QFws2LTuqnXL5eytTkB0EMpd4e7ZZU=,iv:0rn58bbO8ICwqNtZ9VH/U5nG1drrjHImvD3Z1R4GZYc=,tag:LWu8AZJ2S96AMKZ/0dkSww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MVdrbmR1cVovL25VbjZH
            YlFSV2tKNWs2SXluOFNBYnlZOWJQRVY2QmlJCmw0dEJnVGl4NHVSYVdwZVdWcmhx
            MDRITTRSRXF1ampRZnpOViswVG5OaEUKLS0tIERGRG1oSlA3QVQ2a2pxdGlQMjRY
            NlBjZ21ZQTZZSUNBMklSbTkvSXNZb00KgvlmUY3/pCos36FQ6C8aIkeEgkD2ePa5
            LxcMsjw1zIROX83l+1gus70+5Tkf5SgHUZilQcP7xMePpS4wmDu3eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
    lastmodified: "2026-05-22T22:14:10Z"
    mac: ENC[AES256_GCM,data:/wcXcZgsrZVLT5S9XSlReiYps00udlt8G8XHDoRNKggdT81qu714Mu6CDWeup4WOyrlGd0QvufbAZNSoOc51R3V9iYp56QHEOiIF/dpZwdeO5YIPc5ew8O5Mof7/GvLHod74t5gy2FZ+I1Mh4slbrDU68twdO0HWzGj2tkqXQhA=,iv:/MMR5KkGgxnD/Rfn7lacxi7CPSKStPuI/Sbidf2set8=,tag:FPedsQPdLFiD62WK9dKf/Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
