apiVersion: v1
kind: Secret
metadata:
    name: preparr-postgres-backup-s3
    namespace: media
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:+OoJFftycyRp4Pi/h7Gj5gSXhC0RTp5dj6k=,iv:1nw0vtiKr4P9xS3ppWbnmWwkwBYzgRiwt8jvhE56xlg=,tag:cSRCaC8OjCA6iJD5P98PeA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HntKhzp5RtR6OstGd7RrPXSdVbANt3cl5Dw=,iv:mKUyxv/wTnYJx9fJAa7r7poe0p8oMTuAIK9e9nHbn+8=,tag:v2cTia7AMZ+sauFzpGvhtQ==,type:str]
    REGION: ENC[AES256_GCM,data:d4PUTMfL,iv:GVN+WwRd710AK/BQS0Gyf/u9NoTdcB6Q8qwPyOWpNtw=,tag:ZGgQl8ezpSu72ONw/npnzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UXhRK0J5MWpiS1oyN05z
            WERocHNNemE3clpyMGxIVlZ5di90V0VQUFFBCmZMT0E1VzBnVkVpeVVMRS9FeXFW
            UDV6MkdvRFVHM2N4TXN4aW5MWHcrLzAKLS0tIGwrazY3S0t0eFVIOW9QOXNmQml2
            VitpRmFQV2Fud3ZwNk1ZU0w4enZGamcKar2dSdqg17Hx9nI8VptFknCARi4yzDzn
            yh6SZ+U7AJiJVyvX3SePBxAarQS9qMj8PK+h4/7dpMY5S+bl0QHi3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
    lastmodified: "2026-05-22T19:16:57Z"
    mac: ENC[AES256_GCM,data:GsBse5wifAfihaZLpTjxY8Nllzs+jS9OsDyOWs1c8Du76vgUoQb14zVf4MkJqJpn+w0zE4rwfeGqSTE/iKLG5nGPgmiVLxCstjJUkZgxjoa1IhseXAFlg729NuRnttYjaTjJesv7OoiPa42ynuDCI78SlqfYSpOCXs5J8vduDJE=,iv:rxj32fBvznQOje/VCXiB5GT/mJH3DXb1FdW46sGK7nM=,tag:QXsgGDTbqHVZPSNLEKHm+g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
