apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: preparr-postgres
  namespace: media
spec:
  instances: 1

  inheritedMetadata:
    labels:
      velero.io/exclude-from-backup: "true"

  storage:
    size: 10Gi
    storageClass: local-path

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  enableSuperuserAccess: true

  postgresql:
    pg_hba:
      - host all all 10.42.0.0/16 trust

  bootstrap:
    initdb:
      database: sonarr_main
      owner: postgres
      postInitSQL:
        - ALTER USER postgres WITH SUPERUSER
      postInitApplicationSQL:
        - CREATE DATABASE sonarr_log OWNER postgres
        - CREATE DATABASE radarr_main OWNER postgres
        - CREATE DATABASE radarr_log OWNER postgres
        - CREATE DATABASE prowlarr_main OWNER postgres
        - CREATE DATABASE prowlarr_log OWNER postgres
        - CREATE DATABASE bazarr_main OWNER postgres
        - CREATE DATABASE bazarr_log OWNER postgres

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://backups/cnpg/
      endpointURL: http://10.0.0.11:3900
      s3Credentials:
        accessKeyId:
          name: preparr-postgres-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: preparr-postgres-backup-s3
          key: SECRET_ACCESS_KEY
        region:
          name: preparr-postgres-backup-s3
          key: REGION
      wal:
        compression: gzip
      data:
        compression: gzip
