apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: preparr-postgres-backup-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - backup-credentials.sops.yaml
