immich:
  persistence:
    library:
      existingClaim: immich-pvc

redis:
  enabled: true


env:
    REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
    DB_HOSTNAME: "postgres"
    DB_USERNAME: "immich"
    DB_DATABASE_NAME: "immich"
    DB_PASSWORD: "immichpassword"
    IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'