apiVersion: v1
kind: Secret
metadata:
    name: pi-hole-secret
    namespace: pi-hole
    labels:
        app: pi-hole
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:3QYFimwBNhd4,iv:DB/0i+349Kvqr1DUMr+sXxT/liZWmVZ0wUSkRbrGpkY=,tag:tDS3uNjRANJZpnv/NvgSTQ==,type:str]
sops:
    age:
        - recipient: age1887g842zprdv8sculknt80wx4awhfh6mjzst9cxju3lpf9xeq5xslndmcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QUh0VG5NZW1hNlZuTVhv
            NUFpZ0xVVGhoelNVS0R4MmR4eXBwMTl0cGo4CjdhaW85UnM3VmdSU2lycVBWZ3JQ
            a0wxQnFsVCtXY3ByVm5sdjNQaE9hTXMKLS0tIG5KQ1Z0QjJENTZ1bHBnZzZDNXBI
            dDNza2ZMa1Y1VXpVVFFrYnBFcVZ1akEKP/f6KH1WQXBALbx3TU0TUY2nbxRKdmnv
            bEdHPaPMvRyFtWgMHLokM8SD6ea2ag5IRijml06sgs1272Ola0TZgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:30:16Z"
    mac: ENC[AES256_GCM,data:GhVk3jt16aepJbTDmK5O0C1tNNm4PyTX7KO2jm1j757x/x15QDt10hx1LfSvT/J9dDJmKNdBCp6gkqugLDySRt+zyZegw2g2i2Kf74vq1cEhcNpoiI5ZzhlEQ9fiUaqYKR9xxwNbaejJLRuxxH2OjIzkDqcxiA3bk9nOnskj5VI=,iv:JwOnZvo45UPEw9J+Bb1pb1d7bVAbHhjj3EcIMpfIKMs=,tag:s9UOWFfFjSiDQ56/70sCTw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
