apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applicationset.yaml
  - ingress.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    # renovate: datasource=helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm versioning=semver
    version: 4.33.2
    valuesFile: values.yaml
