configs:
  cm:
    kustomize.buildOptions: "--enable-helm --enable-alpha-plugins --enable-exec"
  params:
    server.insecure: true

repoServer:
  env:
    - name: PATH
      value: /ksops/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: SOPS_AGE_KEY_FILE
      value: /home/argocd/.config/sops/age/keys.txt

  volumes:
    - name: ksops-image
      image:
        # renovate: datasource=docker depName=viaductoss/ksops versioning=semver
        reference: viaductoss/ksops:v4.5.1
        pullPolicy: IfNotPresent
    - name: ksops-age-key
      secret:
        secretName: ksops-age-key

  volumeMounts:
    - name: ksops-image
      mountPath: /ksops
      readOnly: true
    - name: ksops-age-key
      mountPath: /home/argocd/.config/sops/age/keys.txt
      subPath: keys.txt
      readOnly: true
